language: python
addons:
  firefox: "52.9.0esr"
env:
  - TEST_SUITE=jenkins
  - TEST_SUITE=harvest
  - TEST_SUITE=harvest2
python:
  - "2.7"
before_install:
  - pip install --upgrade setuptools pip wheel
script:
  - make $TEST_SUITE
